name: github-repo-stats

on:
  schedule:
    - cron: 0 0 * * *  # once a day

jobs:
  pull-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: romanlutz/github-repo-stats
        path: github-repo-stats
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install requirements
      run: pip install -r requirements.txt
      working-directory: github-repo-stats
      shell: bash
    
    - name: Collect repo stats
      run: python collect_stats.py --org fairlearn --repo fairlearn --token "$TOKEN" --file-name ../stats.json
      working-directory: github-repo-stats
      shell: bash
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    - name: Push to repository
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish stats update'
        force-add: 'true'
        files: stats.json
        name: Roman Lutz
        email: rolutz@microsoft.com
    
  deploy-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Clean up build directories
      run: rm -r docs/_build
      shell: bash

    - name: Build webpage
      run: python -m sphinx -b html -j auto docs docs/_build/html
      shell: bash
    
    - name: Push to repository
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish stats update'
        force-add: 'true'
        files: docs/_build/html/*
        name: Roman Lutz
        email: rolutz@microsoft.com
