name: github-repo-stats

on:
  schedule:
    - cron: 0 0 * * *  # once a day
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: fairlearn-stats

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: romanlutz/github-repo-stats
        path: github-repo-stats
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install requirements
      run: pip install -r requirements.txt
      working-directory: github-repo-stats
      shell: bash
    
    - name: Collect repo stats
      run: python collect_stats.py --org fairlearn --repo fairlearn --token "$(ACCESS_TOKEN)" --file-name ../fairlearn-stats/stats.json
      working-directory: github-repo-stats
      shell: bash
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish stats update'
        force-add: 'true'
        files: fairlearn-stats/stats.json
        name: Roman Lutz
        email: rolutz@microsoft.com
